query autocompleteSearchSuggestions($fullText: String!, $searchState: String) {
  autocompleteSearchSuggestions(fullText: $fullText, searchState: $searchState)
    @context(provider: "vtex.search-graphql") {
    searches {
      term
      attributes {
        key
        value
        labelValue
      }
    }
  }
}
