query orderForm {
  orderForm {
    cacheId
    orderFormId
    value
    totalizers {
      id
      name
      value
    }
    items {
      id
      name
      imageUrl
      detailUrl
      skuName
      quantity
      sellingPrice
      listPrice
      parentItemIndex
      parentAssemblyBinding
    }
    shippingData {
      address {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
      }
      availableAddresses {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
      }
    }
    clientProfileData {
      email
      firstName
    }
    storePreferencesData {
      countryCode
      currencyCode
      timeZone
    }
    itemMetadata {
      items {
        id
        name
        skuName
        productId
        refId
        ean
        imageUrl
        detailUrl
        assemblyOptions {
          id
          name
          required
          inputValues
          composition {
            minQuantity
            maxQuantity
          }
        }
      }
    }

  }
}
