#import '../fragments/product.graphql'
#import '../fragments/item.graphql'
#import '../fragments/seller.graphql'
#import '../fragments/commertialOffer.graphql'
#import '../fragments/installment.graphql'

query productSuggestions(
  $fullText: String!
  $facetKey: String
  $facetValue: String
  $origin: String
  $productOriginVtex: Boolean = false
  $simulationBehavior: SimulationBehavior = default
  $hideUnavailableItems: Boolean = false
  $orderBy: String
  $count: Int
  $shippingOptions: [String]
  $variant: String
  $advertisementOptions: AdvertisementOptions
) {
  productSuggestions(
    fullText: $fullText
    facetKey: $facetKey
    facetValue: $facetValue
    origin: $origin
    productOriginVtex: $productOriginVtex
    simulationBehavior: $simulationBehavior
    hideUnavailableItems: $hideUnavailableItems
    orderBy: $orderBy
    count: $count
    shippingOptions: $shippingOptions
    variant: $variant
    advertisementOptions: $advertisementOptions
  ) @context(provider: "vtex.search-graphql") {
    count
    misspelled
    operator
    products {
      ...ProductFragment
      items {
        ...ItemFragment
        sellers {
          ...SellerFragment
          commertialOffer {
            ...CommertialOfferFragment
            Installments {
              ...InstallmentFragment
            }
          }
        }
      }
      selectedProperties {
        key
        value
      }
      rule {
        id
      }
    }
    searchId
  }
}
