fragment product on Product {
  cacheId
  productId
  productName
  linkText
  titleTag
  metaTagDescription
  specificationGroups {
    name
    specifications {
      name
      values
    }
  }
  items {
    itemId
    name
    nameComplete
    referenceId {
      Key
      Value
    }
    measurementUnit
    unitMultiplier
    images {
      imageId
      imageLabel
      imageTag
      imageUrl
      imageText
    }
    sellers {
      sellerId
      sellerName
      commertialOffer {
        Price
        ListPrice
        PriceWithoutDiscount
        RewardValue
        PriceValidUntil
        AvailableQuantity
      }
    }
  }
}
