query search(
  $query: String
  $map: String
  $orderBy: String
  $priceRange: String
  $from: Int
  $to: Int
) {
  productSearchNoSimulations (
    query: $query
    map: $map
    orderBy: $orderBy
    priceRange: $priceRange
    from: $from
    to: $to
  ) @context(provider: "vtex.search-graphql") {
    products {
      cacheId
      productId
      description
      productName
      productReference
      linkText
      brand
      brandId
      link
      categories
      specificationGroups {
        name
        specifications {
          name
          values
        }
      }
      items {
        itemId
        name
        nameComplete
        complementName
        ean
        variations {
          name
          values
        }
        referenceId {
          Key
          Value
        }
        measurementUnit
        unitMultiplier
        images {
          cacheId
          imageId
          imageLabel
          imageTag
          imageUrl
          imageText
        }
        sellers {
          sellerId
          sellerName
          commertialOffer {
            discountHighlights {
              name
            }
            teasers {
              name
              conditions {
                minimumQuantity
                parameters {
                  name
                  value
                }
              }
              effects {
                parameters {
                  name
                  value
                }
              }
            }
            Installments(criteria: MAX) {
              Value
              InterestRate
              TotalValuePlusInterestRate
              NumberOfInstallments
              Name
            }
            Price
            ListPrice
            PriceWithoutDiscount
            RewardValue
            PriceValidUntil
            AvailableQuantity
          }
        }
      }
      productClusters {
        id
        name
      }
      properties {
        name
        values
      }
    }
    recordsFiltered
    breadcrumb {
      name
      href
    }
  }
}
