query searchSuggestions($fullText: String!, $searchState: String) {
  searchSuggestions(fullText: $fullText, searchState: $searchState)
    @context(provider: "vtex.search-graphql") {
    searches {
      term
      count
    }
  }
}
