query searchSuggestions($fullText: String, $selectedFacets: [SelectedFacetInput]) {
  searchSuggestions(fullText: $fullText, selectedFacets: $selectedFacets)
    @context(provider: "vtex.search-graphql") {
    searches {
      term
      count
    }
  }
}
