query search($query: String, $map: String, $orderBy: String, $priceRange: String, $from: Int, $to: Int, $withFacets: Boolean = true) {
  products(query: $query, map: $map, orderBy: $orderBy, priceRange: $priceRange, from: $from, to: $to) {
    cacheId
    categories
    productId
    description
    productName
    linkText
    brand
    link
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images {
        cacheId
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        commertialOffer {
          discountHighlights {
            name
          }
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
        }
      }
    }
    productClusters {
      name
    }
  }
  facets(query: $query, map: $map) @include (if: $withFacets) {
    Departments {
      Quantity
      Name
      Link
      Slug
      selected
    }
    Brands {
      Quantity
      Name
      Link
      Slug
      selected
    }
    SpecificationFilters {
      name
      facets {
        Quantity
        Name
        Link
        Slug
        selected
      }
    }
    CategoriesTrees {
      Id
      Quantity
      Name
      Link
      Slug
      selected
      Children {
        Id
        Quantity
        Name
        Link
        Slug
        selected
        Children {
          Id
          Quantity
          Name
          Link
          Slug
          selected
        }
      }
    }
    PriceRanges {
      Quantity
      Name
      Link
      Slug
    }
  }
}
