query ProductCategoryTree($slug: String, $identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) @context(provider: "vtex.search-graphql") {
    cacheId
    categoryTree {
      id
      name
      href
    }
  }
}
